---
title: "exploration1-questions"
author: "Duu Renn"
date: "August 29, 2016"
output: pdf_document
---

```{r setup, include=FALSE}
require(knitr)
opts_chunk$set(
  tidy=TRUE,     # display code as typed # Changed to true because my comments are too long
  tidy.opts=list(width.cutoff=75),
  size="small",    # slightly smaller font for code
  echo=TRUE,
  results='markup',
  strip.white=TRUE,
  fig.path='figs/fig',
  cache=FALSE,
  highlight=TRUE,
  width.cutoff=132, 
  size='footnotesize',
  out.width='.9\\textwidth',
  fig.retina=FALSE,
  message=FALSE,
  comment=NA)
```

# Questions
As people ask questions, I'll post responses here and push them to the shared folder. You can email me these questions or create an "issue" in the 'uips-stat-share' repository. Note that this is different than the 'explorations' repository -- we should probably try to keep that relatively clutter-free.  

```{r source-530-exploration1, include=F}
tempR <- tempfile(fileext = ".R")
require(knitr)
purl("C:/Users/duu/OneDrive/School/gradstats/uips-stat-share/ps531/exploration1.Rmd", output=tempR)
source(tempR)
unlink(tempR)
```
# 